---
#place xxx with your own .crt and .key
apiVersion: v1
data:
  tls.crt: xxxx
  tls.key: xxxx
kind: Secret
metadata:
  creationTimestamp: null
  name: tls-wildcard-demo
  namespace: demo-gitlab
type: kubernetes.io/tls
